spring:
  application:
    name: WarehouseInventory

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    expiration-minutes: 60

  jackson:
    deserialization:
      use-big-decimal-for-floats: true